version: '2'
services:
  app:
    image: wordpress:4.5
    links:
      - db:mysql
    volumes:
      - ./wp-content/themes:/var/www/html/wp-content/themes
      - ./wp-content/plugins:/var/www/html/wp-content/plugins
      - ./wp-content/uploads:/var/www/html/wp-content/uploads
    networks:
      - public
      - private
    ports:
      - "80:80"
    environment:
      WORDPRESS_DB_NAME: wordpress
      WORDPRESS_DB_USER: wordpress
      WORDPRESS_DB_PASSWORD: wordpress
  db:
    image: mysql:latest
    volumes:
      - db:/var/lib/mysql
    networks:
      - private
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: wordpress
      MYSQL_USER: wordpress
      MYSQL_PASSWORD: wordpress
      MYSQL_ROOT_PASSWORD: wpadmin
networks:
  public:
  private:
volumes:
  db:
